/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rifki fikri
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_282 = new javax.swing.JLabel();
        jTextField1_282 = new javax.swing.JTextField();
        jComboBox1_282 = new javax.swing.JComboBox<>();
        jComboBox2_282 = new javax.swing.JComboBox<>();
        jButton1_282 = new javax.swing.JButton();
        jLabel2_282 = new javax.swing.JLabel();
        jTextField2_282 = new javax.swing.JTextField();
        jLabel3_282 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_282.setText("Program Konversi Suhu");

        jComboBox1_282.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur", " " }));

        jComboBox2_282.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));
        jComboBox2_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_282ActionPerformed(evt);
            }
        });

        jButton1_282.setText("Konversi");
        jButton1_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_282ActionPerformed(evt);
            }
        });

        jLabel2_282.setText("Hasil");

        jTextField2_282.setEditable(false);

        jLabel3_282.setText("ke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_282)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3_282)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2_282, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jButton1_282)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_282)
                            .addComponent(jTextField2_282, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1_282)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_282)
                    .addComponent(jLabel3_282))
                .addGap(48, 48, 48)
                .addComponent(jLabel2_282)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_282ActionPerformed
      String box1 = (String)jComboBox1_282.getSelectedItem();
      String box2 = (String)jComboBox2_282.getSelectedItem();
      //----------------------celcius
      if(box1.equals("Celcius") && box2.equals("Fahrenheit")){
          double c = Double.parseDouble(jTextField1_282.getText());
          
          double f = (double)(c * 1.8 + 32);
          
          jTextField2_282.setText(String.valueOf(f));
      }
      if(box1.equals("Celcius") && box2.equals("Kelvin")){
          double c = Double.parseDouble(jTextField1_282.getText());
          
          double k = (double)(c + 273.15);
          
          jTextField2_282.setText(String.valueOf(k));
      }
      if(box1.equals("Celcius") && box2.equals("Reamur")){
          double c = Double.parseDouble(jTextField1_282.getText());
          
          double r = (double)(0.8*c);
          
          jTextField2_282.setText(String.valueOf(r));
      }
      
      if(box1.equals("Celcius") && box2.equals("Celcius")){
          double c = Double.parseDouble(jTextField1_282.getText());
          
          jTextField2_282.setText(String.valueOf(c));
      }
      //--------------------------------------fahrenheit
      if(box1.equals("Fahrenheit")&& box2.equals("Celcius")){
          double f = Double.parseDouble(jTextField1_282.getText());
          
          double  c = (double)((f-32)*5/9);
          
          jTextField2_282.setText(String.valueOf(c));
      }else if(box1.equals("Fahrenheit")&& box2.equals("Kelvin")){
          double f = Double.parseDouble(jTextField1_282.getText());
          
          double  k = (double)((f-32)*5/9+273.15);
          
          jTextField2_282.setText(String.valueOf(k));
      }else if(box1.equals("Fahrenheit")&& box2.equals("Reamur")){
          double f = Double.parseDouble(jTextField1_282.getText());
          
          double  r = (double)(0.4444444444444444*(f-32));
          
          jTextField2_282.setText(String.valueOf(r));
      }
      else if(box1.equals("Fahrenheit")&& box2.equals("Fahrenheit")){
          double f = Double.parseDouble(jTextField1_282.getText());
          
          jTextField2_282.setText(String.valueOf(f));
      }
      //---------------------------------------------------kelvin
      if(box1.equals("Kelvin") && box2.equals("Celcius")){
          double k = Double.parseDouble(jTextField1_282.getText());
          
          double c = (double)(0 - 273.15);
          
          jTextField2_282.setText(String.valueOf(c));
      }else if(box1.equals("Kelvin")&& box2.equals("Fahrenheit")){
          double k = Double.parseDouble(jTextField1_282.getText());
          
          double  f = (double)(0-273.15)* 9/5 + 32;
          
          jTextField2_282.setText(String.valueOf(f));
      }
      else if(box1.equals("Kelvin")&& box2.equals("Reamur")){
          double k = Double.parseDouble(jTextField1_282.getText());
          
          double  r = (double) 0.8*(k-273);
          
          jTextField2_282.setText(String.valueOf(r));
      }
      else if(box1.equals("Kelvin")&& box2.equals("Kelvin")){
          double k = Double.parseDouble(jTextField1_282.getText());
          
          jTextField2_282.setText(String.valueOf(k));
      }
      //---------------------------------------------reamur
      if(box1.equals("Reamur") && box2.equals("Celcius")){
          double r = Double.parseDouble(jTextField1_282.getText());
          
          double c = (double) 1.25*r;
          
          jTextField2_282.setText(String.valueOf(c));
      }else if(box1.equals("Reamur") && box2.equals("Fahrenheit")){
          double r = Double.parseDouble(jTextField1_282.getText());
          
          double f = (double) (2.25+r)+32;
          
          jTextField2_282.setText(String.valueOf(f));
      }
      else if(box1.equals("Reamur") && box2.equals("Kelvin")){
          double r = Double.parseDouble(jTextField1_282.getText());
          
          double f = (double) (r*5/4 + 273.15);
          
          jTextField2_282.setText(String.valueOf(f));
      }else if(box1.equals("Reamur") && box2.equals("Kelvin")){
          double r = Double.parseDouble(jTextField1_282.getText());
         
          jTextField2_282.setText(String.valueOf(r));
      }
      
    }//GEN-LAST:event_jButton1_282ActionPerformed

    private void jComboBox2_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_282ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2_282ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_282;
    private javax.swing.JComboBox<String> jComboBox1_282;
    private javax.swing.JComboBox<String> jComboBox2_282;
    private javax.swing.JLabel jLabel1_282;
    private javax.swing.JLabel jLabel2_282;
    private javax.swing.JLabel jLabel3_282;
    private javax.swing.JTextField jTextField1_282;
    private javax.swing.JTextField jTextField2_282;
    // End of variables declaration//GEN-END:variables
}
